[package]
name = "ctftools"
version = "0.1.0"
authors = ["prrrple team <https://github.com/prrrple>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]
ansi_term = "0.12.1"
clap = "2.33.3"
num_enum = "0.5.1"
 